# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 11:46
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrip_code', models.CharField(blank=True, max_length=255, null=True)),
                ('scrip_name', models.CharField(blank=True, max_length=255, null=True)),
                ('yahoo_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Only 10 digits are allowed. Invalid Number', regex='^\\d{10}$')], verbose_name='Phone Number')),
                ('date_joined', models.DateTimeField(blank=True, null=True, verbose_name='Joined Date')),
                ('commited_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('client_code', models.CharField(blank=True, max_length=255, null=True)),
                ('broker', models.CharField(blank=True, max_length=255, null=True)),
                ('broker_email', models.CharField(blank=True, max_length=255, null=True)),
                ('broker_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Only 10 digits are allowed. Invalid Number', regex='^\\d{10}$')], verbose_name='Broker Number')),
                ('pan', models.CharField(blank=True, max_length=255, null=True)),
                ('fixed_fee_cost', models.CharField(blank=True, max_length=255, null=True)),
                ('performance_cost', models.CharField(blank=True, max_length=255, null=True)),
                ('fee_structure', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_load', models.CharField(blank=True, max_length=255, null=True)),
                ('exit_load', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrip_code', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('open_value', models.FloatField(blank=True, default=0.0, null=True)),
                ('high_value', models.FloatField(blank=True, default=0.0, null=True)),
                ('low_value', models.FloatField(blank=True, default=0.0, null=True)),
                ('close_value', models.FloatField(blank=True, default=0.0, null=True)),
                ('volume', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrip_code', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now=True, null=True, verbose_name='Created Date')),
                ('date_updated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='updated Date')),
                ('quantity', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
